// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Number   string `json:"number"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"access_token"`
	Expiration  string `json:"expiration"`
}
